config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'

    resources :articles, except: [:index, :show]
    resources :comments, only: [:destroy]
    scope path: "articles/:article_id", as: :article do
      get "tags/remove/:id", to: "tags#remove", as: :remove_tag
    end
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"

  resources :articles, only: [:index, :show] do
    resources :comments 
  end

  scope path: "articles/:article_id", as: :article do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :author, class_name: "Admin"
    has_one_attached :attachment
    has_many :comments, dependent: :destroy
    has_and_belongs_to_many :tags
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :text, presence: true

  scope :persisted, -> { where.not(id: nil) }
  scope :ordered, -> { order(created_at: :asc) }
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  def index
  end

  private

  def authorize_admin!
    authenticate_admin!

    unless current_admin.admin?
      redirect_to root_path, alert: "You must be an admin to do that!"
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController

  def new
    @article = Article.new
  end

  def create
      @article = Article.new(article_params)
      @article.author = current_admin
      @article.tags = processed_tags


      if @article.save
          flash[:notice] = "Article has been uploaded!"
          redirect_to @article
      else
          flash.now[:alert] = "Article has not been uploaded."
          render "new"
      end      
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    @article.tags << processed_tags

    flash[:notice] = "Article has been updated."
    redirect_to @article
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    flash[:notice] = "Article has been deleted."
    redirect_to articles_path
  end

  private

  def article_params
      params.require(:article).permit(:title, :description, :attachment)
  end

  def set_article
    @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The article you were looking for could not be found."
    redirect_to articles_path
  end

  def processed_tags
    params[:tag_names].split(",").map do |tag|
      Tag.find_or_initialize_by(name: tag.strip)
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
    before_action :set_article, only: [:destroy]

    def destroy
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        flash[:notice] = "Comment has been deleted."

        redirect_to @article
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def comment_params
        params.require(:comment).permit(:text, :name)
    end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
    def remove
        @article = Article.find(params[:article_id])
        @tag = Tag.find(params[:id])

        @article.tags.destroy(@tag)
        redirect_to edit_admin_article_path(@article)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: %i(show)

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
        @comment = @article.comments.build
    end

    private

    def set_article
        @article = Article.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The article you were looking for could not be found."
        redirect_to articles_path
    end

    def article_params
        params.require(:article).permit(:title, :description, :attachment)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article

    def create
        @comment = @article.comments.build(comment_params)
        
        if @comment.save
            flash[:notice] = "Comment has been created."
            redirect_to @article
        else
            flash.now[:alert] = "Comment has not been created."
            render "articles/show"
        end
    end

    private

    def set_article
        @article = Article.find(params[:article_id])
    end

    def comment_params
        params.require(:comment).permit(:text, :name)
    end
end

app/controllers/tags_controller.rb
# class TagsController < ApplicationController
#     def remove
#         @article = Article.find(params[:article_id])
#         @tag = Tag.find(params[:id])

#         @article.tags.destroy(@tag)
#         render edit_admin_article_path(@article)
#     end
# end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def admins_only(&block)
        block.call if current_admin.try(:admin?)
    end

    def title(*parts)
        unless parts.empty?
            content_for :title do
                (parts << "Article")
            end
        end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/application/index.html.erb
<ul>
<li><%= link_to "Upload Article", new_admin_article_path %></li>
</ul>

app/views/admin/articles/_form.html.erb
<%= bootstrap_form_with(model: [:admin, article], local: true) do |form| %>
    <%= form.text_field :title %>
    <%= form.text_field :description %>
    <%= form.file_field :attachment, label: "File" %>

    <div class="form-group tags">
        <div><%= label_tag :tag_names, "Tags" %></div>
        <%= render @article.tags, article: @article %>
        <%= text_field_tag :tag_names, "", class: "form-control" %>
    </div>

    <%= form.primary %>
<% end %>

app/views/admin/articles/edit.html.erb
<h1> Editing Article </h1>

<%= render "form", article: @article %>

app/views/admin/articles/index.html.erb
<h1>Admin::Articles#index</h1>
<p>Find me in app/views/admin/articles/index.html.erb</p>

app/views/admin/articles/new.html.erb
<h1> New Article </h1>

<%= render "form", article: @article %>

app/views/admin/tags/_tag.html.erb
<div class="edittag">
    <%= link_to "<span></span>".html_safe, admin_article_remove_tag_path(article, tag), 
    method: :get, remote: true, 
    class: "remove", title: "Remove tag" %>
    <%= tag.name %>
</div>

app/views/articles/_form.html.erb
<%= bootstrap_form_with(model: article, local: true) do |form| %>
    <%= form.text_field :title %>
    <%= form.text_field :description %>
    <%= form.file_field :attachment, label: "File" %>

    <%= form.primary %>
<% end %>

app/views/articles/index.html.erb
<h1> Welcome to My Website!</h1>
<p> My name is Seth Linex, I am an aspiring backend web developer with interests in encryption and cybersecurity. Below you will find my GitHub, LinkedIn, resume, and some articles and tutorials I've written.</p>

<h1> List of Articles: </h1>

<div class="articles">
    <% @articles.each do |article| %>
        <h2><%= link_to article.title, article %></h2>
    <% end %>
</div>

app/views/articles/show.html.erb
<div class="article">
<% title @article.title, "Articles" %>
<h1><%= @article.title %></h1>
    <table class="attributes">
            <tr>
                <td><%= @article.author.email %></td>
            </tr>
            <tr>
                <th> Uploaded on: </th>
                <td><%= @article.created_at %></td>
            </tr>
        <% if @article.tags.any? %>
            <tr>
                <th> Tags: </th>
                <td class="tags"><%= render @article.tags, article: @article %></td>
            </tr>
        <% end %>
    </table>

<p><%= simple_format(@article.description) %></p>

<% if @article.attachment.present? %>
    <h4> Attachment </h4>
    <div class="attachment">
        <p>
            <%= link_to @article.attachment.filename, rails_blob_path(@article.attachment, disposition: 'attachment') %>
        </p>
    </div>
<% end %>

<div class="comments">
    <header>
        <h3> Comments </h3>
    </header>

<% comments = @article.comments.persisted.ordered %>
<% if comments.any? %>
    <%= render comments %>
<% else %>
    <p> No comments, yet! </p>
<% end %>

<%= render "comments/form", article: @article, comment: @comment %>

<% admins_only do %>
    <ul class="actions">
        <li><%= link_to "Edit Article", edit_admin_article_path(@article),
                class: "edit" %></li>

        <li><%= link_to "Delete Article", admin_article_path(@article),
                method: :delete,
                data: { confirm: "Delete article?" },
                class: "delete" %></li>
    </ul>
<% end %>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
    <div class="author">
        <%= time_ago_in_words(comment.created_at) %> ago 
        &mdash; <%= simple_format(comment.name) %>
    </div>
    <div class="text">
        <%= simple_format(comment.text) %>
    </div>

    <% admins_only do %>

    <ul class="actions">
    <li><%= button_to "Delete Comment", admin_comment_path(comment),
                method: :delete,
                data: { confirm: "Delete comment?" },
                class: "delete" %></li>
    </ul>
    
    <% end %>
</div>

app/views/comments/_form.html.erb
<header>
    <h3> New Comment </h3>
</header>

<%= bootstrap_form_with model: [article, comment], local: true do |f| %>
    <%= f.text_area :name %>
    <%= f.text_area :text %>
    <%= f.primary %>
<% end %>

app/views/tags/_tag.html.erb
<div class="tag">
    <%= link_to "<span></span>".html_safe, admin_article_remove_tag_path(article, tag), 
    method: :get, remote: true, 
    class: "remove", title: "Remove tag" %>
    <%= tag.name %>
</div>